name: Test & Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: latest
    - name: Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm lint
    - run: pnpm test -- --coverage
    - run: pnpm build
